name: Build OpenSSL for Android (PIC)

on:
  workflow_dispatch:
    inputs:
      openssl_version:
        description: "OpenSSL version"
        required: true
        default: "3.0.18"
      api_level:
        description: "Android API level"
        required: true
        default: "34"
      abis:
        description: "arm64-v8a,armeabi-v7a,x86_64"
        required: true
        default: "arm64-v8a"
      ndk_full:
        description: "NDK full version for sdkmanager (e.g. 26.1.10909125)"
        required: true
        default: "26.1.10909125"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_LEVEL: ${{ inputs.api_level }}
      OPENSSL_VERSION: ${{ inputs.openssl_version }}
      NDK_FULL: ${{ inputs.ndk_full }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (Perl/make + Android cmdline-tools deps)
        run: |
          sudo apt-get update
          sudo apt-get install -y perl make build-essential curl unzip zip

      # ▼ ここがポイント：SDK Manager で NDK をインストール
      - name: Install Android SDK cmdline-tools + NDK
        run: |
          set -e
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p "$ANDROID_SDK_ROOT"
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          # cmdline-tools は 'latest' サブフォルダに配置するのがコツ
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platforms;android-${API_LEVEL}" "platform-tools" "ndk;${NDK_FULL}"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/${NDK_FULL}" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/ndk/${NDK_FULL}/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Download OpenSSL source
        run: |
          curl -L -o openssl.tar.gz "https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz"
          mkdir src && tar -xf openssl.tar.gz -C src
          echo "OPENSSL_SRC=$(echo $GITHUB_WORKSPACE/src/openssl-*)" >> $GITHUB_ENV

      - name: Build (PIC, static)
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
          OPENSSL_SRC: ${{ env.OPENSSL_SRC }}
        run: |
          set -e
          IFS=',' read -ra ABIS <<< "${{ inputs.abis }}"
          for ABI in "${ABIS[@]}"; do
            case "$ABI" in
              arm64-v8a) TARGET=android-arm64;  TRIPLE=aarch64-linux-android ;;
              armeabi-v7a) TARGET=android-arm;  TRIPLE=armv7a-linux-androideabi ;;
              x86_64) TARGET=android-x86_64; TRIPLE=x86_64-linux-android ;;
              *) echo "Unsupported ABI: $ABI"; exit 1 ;;
            esac

            cd "$OPENSSL_SRC"
            make clean || true

            export CC="clang"
            export CXX="clang++"
            export AR="llvm-ar"
            export RANLIB="llvm-ranlib"
            export CFLAGS="-fPIC --target=${TRIPLE}${API_LEVEL} -D__ANDROID_API__=${API_LEVEL}"
            export CXXFLAGS="${CFLAGS}"
            export LDFLAGS="--target=${TRIPLE}${API_LEVEL}"

            perl Configure "$TARGET" -D__ANDROID_API__=${API_LEVEL} no-shared no-tests no-comp no-hw no-engine
            make -j$(nproc)

            OUT="$GITHUB_WORKSPACE/out/$ABI"
            mkdir -p "$OUT/include"
            cp -v libcrypto.a "$OUT/"
            cp -rv include/* "$OUT/include/"

            git -C "$OPENSSL_SRC" clean -fdx >/dev/null 2>&1 || true
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openssl-android-static-${{ inputs.openssl_version }}-api${{ inputs.api_level }}
          path: out/**
